name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: build test
      run: g++ -std=c++17 -Wall -Wextra -Werror -pedantic-errors -O3 -otest test.cpp

    - name: run test
      run: ./test
